//! Integration tests for the full pbip2dbt pipeline.
//!
//! These tests create in-memory ZIP fixtures that mimic a PBIP structure,
//! run the full pipeline, and verify the generated dbt project.

use pbip2dbt::config::Config;
use std::io::Write;
use std::path::PathBuf;
use tempfile::TempDir;
use zip::write::SimpleFileOptions;

/// Create a minimal PBIP zip in a temp directory.
/// Returns the path to the zip file.
fn create_test_zip(tables_tmdl: &[(&str, &str)], relationships_tmdl: Option<&str>) -> (TempDir, PathBuf) {
    let dir = TempDir::new().expect("create temp dir");
    let zip_path = dir.path().join("test_model.zip");

    let file = std::fs::File::create(&zip_path).expect("create zip file");
    let mut zip_writer = zip::ZipWriter::new(file);
    let options = SimpleFileOptions::default();

    // Write model.tmdl
    let model_tmdl = "model Model\n\tsource = powerBi\n";
    zip_writer
        .start_file("TestModel.SemanticModel/definition/model.tmdl", options)
        .expect("start model.tmdl");
    zip_writer
        .write_all(model_tmdl.as_bytes())
        .expect("write model.tmdl");

    // Write table files
    for (filename, content) in tables_tmdl {
        let path = format!(
            "TestModel.SemanticModel/definition/tables/{filename}"
        );
        zip_writer.start_file(&path, options).expect("start table file");
        zip_writer
            .write_all(content.as_bytes())
            .expect("write table file");
    }

    // Write relationships if provided
    if let Some(rels) = relationships_tmdl {
        zip_writer
            .start_file(
                "TestModel.SemanticModel/definition/relationships.tmdl",
                options,
            )
            .expect("start relationships");
        zip_writer
            .write_all(rels.as_bytes())
            .expect("write relationships");
    }

    zip_writer.finish().expect("finish zip");

    (dir, zip_path)
}

fn make_config(input: PathBuf, output: PathBuf) -> Config {
    Config {
        input,
        output,
        adapter: "postgres".to_string(),
        project_name: "test_project".to_string(),
        source_name: Some("test_source".to_string()),
        schema: "raw".to_string(),
        materialization_default: "view".to_string(),
        skip_measures: false,
        skip_calculated_tables: false,
        skip_calculated_columns: false,
        skip_tests: false,
        confidence_threshold: 0.0,
        verbose: false,
        dry_run: false,
    }
}

#[test]
fn simple_import_table() {
    let tmdl = r#"table Sales
	lineageTag: abcd-1234

	column OrderId
		dataType: int64
		sourceColumn: OrderId
		lineageTag: col-001

	column Amount
		dataType: double
		sourceColumn: Amount
		lineageTag: col-002

	partition 'Sales' = m
		mode: import
		expression =
			let
			    Source = Sql.Database("localhost", "adventureworks"),
			    dbo_Sales = Source{[Schema="dbo",Item="Sales"]}[Data]
			in
			    dbo_Sales
"#;

    let (_dir, zip_path) = create_test_zip(&[("Sales.tmdl", tmdl)], None);
    let output_dir = TempDir::new().expect("create output dir");
    let config = make_config(zip_path, output_dir.path().to_path_buf());

    let report = pbip2dbt::run(&config).expect("pipeline should succeed");

    // Verify report
    assert_eq!(report.summary.tables_total, 1);
    assert_eq!(report.adapter, "postgres");

    // Verify generated files
    assert!(output_dir.path().join("dbt_project.yml").exists());
    assert!(output_dir.path().join("packages.yml").exists());
    assert!(output_dir.path().join("models").join("staging").join("stg_sales.sql").exists());
    assert!(output_dir.path().join("models").join("_models.yml").exists());
    assert!(output_dir.path().join("translation_report.json").exists());

    // Verify staging SQL content
    let sql = std::fs::read_to_string(
        output_dir.path().join("models").join("staging").join("stg_sales.sql"),
    )
    .expect("read staging sql");
    assert!(sql.contains("source('test_source', 'sales')"));
    assert!(sql.contains("Auto-generated by pbip2dbt"));
    assert!(sql.contains("select"));
    assert!(sql.contains("from source"));

    // Verify dbt_project.yml
    let project = std::fs::read_to_string(output_dir.path().join("dbt_project.yml"))
        .expect("read project yml");
    assert!(project.contains("name: 'test_project'"));
    assert!(project.contains("materialized: view"));
}

#[test]
fn table_with_measure() {
    let tmdl = r#"table Sales
	lineageTag: abcd-1234

	measure 'Total Revenue' =
		SUM(Sales[Revenue])
		formatString: #,##0.00

	column Revenue
		dataType: double
		sourceColumn: Revenue
		lineageTag: col-001

	partition 'Sales' = m
		mode: import
		expression =
			let
			    Source = Sql.Database("server", "db"),
			    dbo_Sales = Source{[Schema="dbo",Item="Sales"]}[Data]
			in
			    dbo_Sales
"#;

    let (_dir, zip_path) = create_test_zip(&[("Sales.tmdl", tmdl)], None);
    let output_dir = TempDir::new().expect("create output dir");
    let config = make_config(zip_path, output_dir.path().to_path_buf());

    let report = pbip2dbt::run(&config).expect("pipeline should succeed");
    assert_eq!(report.summary.tables_total, 1);
    assert_eq!(report.summary.measures_total, 1);

    // Verify schema file contains the measure
    let schema = std::fs::read_to_string(output_dir.path().join("models").join("_models.yml"))
        .expect("read schema");
    assert!(schema.contains("total_revenue") || schema.contains("Total Revenue"));
    assert!(schema.contains("measures"));
}

#[test]
fn table_with_relationships() {
    let sales_tmdl = r#"table Sales
	lineageTag: s-001

	column ProductId
		dataType: int64
		sourceColumn: ProductId
		lineageTag: col-001

	partition 'Sales' = m
		mode: import
		expression =
			let
			    Source = Sql.Database("server", "db"),
			    dbo_Sales = Source{[Schema="dbo",Item="Sales"]}[Data]
			in
			    dbo_Sales
"#;
    let products_tmdl = r#"table Products
	lineageTag: p-001

	column ProductId
		dataType: int64
		sourceColumn: ProductId
		lineageTag: col-001

	column ProductName
		dataType: string
		sourceColumn: ProductName
		lineageTag: col-002

	partition 'Products' = m
		mode: import
		expression =
			let
			    Source = Sql.Database("server", "db"),
			    dbo_Products = Source{[Schema="dbo",Item="Products"]}[Data]
			in
			    dbo_Products
"#;

    let rels = r#"relationship rel_sales_products
	fromColumn: Sales.ProductId
	toColumn: Products.ProductId
"#;

    let (_dir, zip_path) = create_test_zip(
        &[("Sales.tmdl", sales_tmdl), ("Products.tmdl", products_tmdl)],
        Some(rels),
    );
    let output_dir = TempDir::new().expect("create output dir");
    let config = make_config(zip_path, output_dir.path().to_path_buf());

    let report = pbip2dbt::run(&config).expect("pipeline should succeed");
    assert_eq!(report.summary.tables_total, 2);
    assert_eq!(report.summary.relationships_total, 1);

    // Check relationship test file
    let rel_tests_path = output_dir
        .path()
        .join("models")
        .join("_relationships_tests.yml");
    assert!(rel_tests_path.exists(), "relationships test file should exist");
    let rel_tests = std::fs::read_to_string(&rel_tests_path).expect("read rel tests");
    assert!(rel_tests.contains("relationships"));
}

#[test]
fn dry_run_produces_no_files() {
    let tmdl = r#"table Sales
	lineageTag: s-001
	column Id
		dataType: int64
		sourceColumn: Id
		lineageTag: col-001
	partition 'Sales' = m
		mode: import
		expression =
			let
			    Source = Sql.Database("server", "db"),
			    dbo_Sales = Source{[Schema="dbo",Item="Sales"]}[Data]
			in
			    dbo_Sales
"#;

    let (_dir, zip_path) = create_test_zip(&[("Sales.tmdl", tmdl)], None);
    let output_dir = TempDir::new().expect("create output dir");
    let mut config = make_config(zip_path, output_dir.path().to_path_buf());
    config.dry_run = true;

    let report = pbip2dbt::run(&config).expect("pipeline should succeed");
    assert_eq!(report.summary.tables_total, 1);

    // No files should be written
    assert!(!output_dir.path().join("dbt_project.yml").exists());
    assert!(!output_dir.path().join("models").exists());
}

#[test]
fn determinism_two_runs_identical() {
    let tmdl = r#"table Customers
	lineageTag: c-001

	column CustomerId
		dataType: int64
		sourceColumn: CustomerId
		lineageTag: col-001

	column CustomerName
		dataType: string
		sourceColumn: CustomerName
		lineageTag: col-002

	measure 'Customer Count' =
		COUNTROWS(Customers)

	partition 'Customers' = m
		mode: import
		expression =
			let
			    Source = Sql.Database("server", "db"),
			    dbo_Customers = Source{[Schema="dbo",Item="Customers"]}[Data]
			in
			    dbo_Customers
"#;

    let (_dir, zip_path) = create_test_zip(&[("Customers.tmdl", tmdl)], None);

    let output1 = TempDir::new().expect("create output dir 1");
    let output2 = TempDir::new().expect("create output dir 2");

    let config1 = make_config(zip_path.clone(), output1.path().to_path_buf());
    let config2 = make_config(zip_path, output2.path().to_path_buf());

    pbip2dbt::run(&config1).expect("run 1");
    pbip2dbt::run(&config2).expect("run 2");

    // Compare staging SQL files
    let sql1 = std::fs::read_to_string(
        output1.path().join("models").join("staging").join("stg_customers.sql"),
    )
    .expect("read sql1");
    let sql2 = std::fs::read_to_string(
        output2.path().join("models").join("staging").join("stg_customers.sql"),
    )
    .expect("read sql2");
    assert_eq!(sql1, sql2, "Two runs should produce identical staging SQL");

    // Compare dbt_project.yml
    let proj1 = std::fs::read_to_string(output1.path().join("dbt_project.yml")).expect("read p1");
    let proj2 = std::fs::read_to_string(output2.path().join("dbt_project.yml")).expect("read p2");
    assert_eq!(proj1, proj2, "Two runs should produce identical project yml");

    // Compare schema
    let schema1 = std::fs::read_to_string(output1.path().join("models").join("_models.yml")).expect("read s1");
    let schema2 = std::fs::read_to_string(output2.path().join("models").join("_models.yml")).expect("read s2");
    assert_eq!(schema1, schema2, "Two runs should produce identical schema");
}

#[test]
fn multiple_adapters_produce_correct_syntax() {
    let tmdl = r#"table Sales
	lineageTag: s-001
	column Id
		dataType: int64
		sourceColumn: Id
		lineageTag: col-001
	partition 'Sales' = m
		mode: import
		expression =
			let
			    Source = Sql.Database("server", "db"),
			    dbo = Source{[Schema="dbo",Item="Sales"]}[Data]
			in
			    dbo
"#;

    let (_dir, zip_path) = create_test_zip(&[("Sales.tmdl", tmdl)], None);

    for adapter in &["postgres", "snowflake", "bigquery", "sqlserver"] {
        let output_dir = TempDir::new().expect("create output dir");
        let mut config = make_config(zip_path.clone(), output_dir.path().to_path_buf());
        config.adapter = adapter.to_string();

        let report = pbip2dbt::run(&config).expect(&format!("pipeline should succeed for {adapter}"));
        assert_eq!(report.adapter, *adapter);

        // Verify output exists
        assert!(
            output_dir.path().join("dbt_project.yml").exists(),
            "dbt_project.yml should exist for {adapter}"
        );
        assert!(
            output_dir.path().join("models").join("staging").join("stg_sales.sql").exists(),
            "staging SQL should exist for {adapter}"
        );

        // Verify adapter name appears in the SQL header
        let sql = std::fs::read_to_string(
            output_dir.path().join("models").join("staging").join("stg_sales.sql"),
        )
        .expect("read sql");
        assert!(
            sql.contains(&format!("Adapter: {adapter}")),
            "SQL should mention adapter: {adapter}"
        );
    }
}

#[test]
fn empty_zip_returns_error() {
    let dir = TempDir::new().expect("create temp dir");
    let zip_path = dir.path().join("empty.zip");

    let file = std::fs::File::create(&zip_path).expect("create zip");
    let zip_writer = zip::ZipWriter::new(file);
    zip_writer.finish().expect("finish zip");

    let output_dir = TempDir::new().expect("create output dir");
    let config = make_config(zip_path, output_dir.path().to_path_buf());

    let result = pbip2dbt::run(&config);
    assert!(result.is_err(), "empty zip should error");
}

#[test]
fn no_semantic_model_folder_returns_error() {
    let dir = TempDir::new().expect("create temp dir");
    let zip_path = dir.path().join("wrong_structure.zip");

    let file = std::fs::File::create(&zip_path).expect("create zip");
    let mut zip_writer = zip::ZipWriter::new(file);
    let options = SimpleFileOptions::default();

    zip_writer
        .start_file("some_random_file.txt", options)
        .expect("start");
    zip_writer
        .write_all(b"not a pbip file")
        .expect("write");
    zip_writer.finish().expect("finish");

    let output_dir = TempDir::new().expect("create output dir");
    let config = make_config(zip_path, output_dir.path().to_path_buf());

    let result = pbip2dbt::run(&config);
    assert!(result.is_err(), "missing SemanticModel should error");
    let err_msg = format!("{}", result.unwrap_err());
    assert!(
        err_msg.contains("E002") || err_msg.contains("SemanticModel"),
        "error should mention missing structure: {err_msg}"
    );
}

#[test]
fn path_traversal_rejected() {
    let dir = TempDir::new().expect("create temp dir");
    let zip_path = dir.path().join("traversal.zip");

    let file = std::fs::File::create(&zip_path).expect("create zip");
    let mut zip_writer = zip::ZipWriter::new(file);
    let options = SimpleFileOptions::default();

    // Write a definition folder first so it's found
    zip_writer
        .start_file("Test.SemanticModel/definition/model.tmdl", options)
        .expect("start model");
    zip_writer
        .write_all(b"model Model\n")
        .expect("write model");

    // Write a path traversal entry
    zip_writer
        .start_file("Test.SemanticModel/definition/../../../etc/passwd", options)
        .expect("start traversal");
    zip_writer.write_all(b"evil").expect("write evil");
    zip_writer.finish().expect("finish");

    let output_dir = TempDir::new().expect("create output dir");
    let config = make_config(zip_path, output_dir.path().to_path_buf());

    let result = pbip2dbt::run(&config);
    assert!(result.is_err(), "path traversal should be rejected");
    let err_msg = format!("{}", result.unwrap_err());
    assert!(
        err_msg.contains("E003") || err_msg.contains("traversal"),
        "error should mention path traversal: {err_msg}"
    );
}

#[test]
fn skip_measures_flag_works() {
    let tmdl = r#"table Sales
	lineageTag: s-001
	measure 'Total' = SUM(Sales[Amount])
	column Amount
		dataType: double
		sourceColumn: Amount
		lineageTag: col-001
	partition 'Sales' = m
		mode: import
		expression =
			let
			    Source = Sql.Database("server", "db"),
			    dbo = Source{[Schema="dbo",Item="Sales"]}[Data]
			in
			    dbo
"#;

    let (_dir, zip_path) = create_test_zip(&[("Sales.tmdl", tmdl)], None);
    let output_dir = TempDir::new().expect("create output dir");
    let mut config = make_config(zip_path, output_dir.path().to_path_buf());
    config.skip_measures = true;

    let report = pbip2dbt::run(&config).expect("pipeline should succeed");
    // Measures total still counted from the model, but none translated
    assert_eq!(report.summary.measures_total, 1);
    // Schema should not contain measure translations
    let schema = std::fs::read_to_string(output_dir.path().join("models").join("_models.yml"))
        .expect("read schema");
    assert!(!schema.contains("measures:"), "measures should be skipped in schema");
}
