//! Generate dbt staging and calculated table `.sql` model files.

use crate::error::PbipError;
use crate::{CalcTableTranslation, MTranslation};
use std::path::Path;

/// Write staging model SQL files.
pub fn write_staging_models(
    translations: &[MTranslation],
    output: &Path,
) -> Result<(), PbipError> {
    let staging_dir = output.join("models").join("staging");

    for t in translations {
        let filename = format!("stg_{}.sql", t.table_name);
        super::write_file(&staging_dir.join(&filename), &t.staging_sql)?;
    }

    Ok(())
}

/// Write calculated table model SQL files.
pub fn write_calc_table_models(
    calc_tables: &[CalcTableTranslation],
    output: &Path,
) -> Result<(), PbipError> {
    let intermediate_dir = output.join("models").join("intermediate");

    for ct in calc_tables {
        let version = env!("CARGO_PKG_VERSION");
        let sql = format!(
            "-- Auto-generated by pbip2dbt v{version}\n\
             -- Calculated table: {original}\n\
             -- Original DAX: {dax}\n\
             -- Confidence: {confidence:.2}\n\
             -- DO NOT EDIT — regenerate from PBIP source\n\n\
             {sql}\n",
            original = ct.original_name,
            dax = ct.original_dax.trim(),
            confidence = ct.confidence,
            sql = ct.translated_sql,
        );

        let filename = format!("int_{}.sql", ct.name);
        super::write_file(&intermediate_dir.join(&filename), &sql)?;
    }

    Ok(())
}
