//! Generate `dbt_project.yml` and `packages.yml`.

use crate::config::Config;
use crate::error::PbipError;
use std::path::Path;

/// Write `dbt_project.yml`.
pub fn write_project_yml(config: &Config, output: &Path) -> Result<(), PbipError> {
    let version = env!("CARGO_PKG_VERSION");
    let content = format!(
        r#"# Auto-generated by pbip2dbt v{version}
# https://docs.getdbt.com/reference/project-configs

name: '{project_name}'
version: '1.0.0'
config-version: 2

profile: '{project_name}'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  {project_name}:
    staging:
      +materialized: {materialization}
    intermediate:
      +materialized: view
"#,
        project_name = config.project_name,
        materialization = config.materialization_default,
    );

    super::write_file(&output.join("dbt_project.yml"), &content)
}

/// Write packages.yml.
pub fn write_packages_yml(output: &Path) -> Result<(), PbipError> {
    let content = r#"# Auto-generated by pbip2dbt
packages:
  - package: dbt-labs/dbt_utils
    version: [">=1.0.0", "<2.0.0"]
"#;
    super::write_file(&output.join("packages.yml"), content)
}
