//! Generate `_models.yml` schema files with column definitions, measures, and tests.

use crate::config::Config;
use crate::error::PbipError;
use crate::naming::sanitize_identifier;
use crate::tmdl::ast::{Relationship, SemanticModel};
use crate::{DaxTranslations, MTranslation};
use std::path::Path;

/// Write schema YAML file for models.
pub fn write_schema(
    config: &Config,
    model: &SemanticModel,
    m_translations: &[MTranslation],
    dax_translations: &DaxTranslations,
    _source_name: &str,
    output: &Path,
) -> Result<(), PbipError> {
    let version = env!("CARGO_PKG_VERSION");
    let mut yaml = String::new();
    yaml.push_str(&format!("# Auto-generated by pbip2dbt v{version}\n"));
    yaml.push_str("version: 2\n\n");
    yaml.push_str("models:\n");

    for t in m_translations {
        yaml.push_str(&format!("  - name: stg_{}\n", t.table_name));
        yaml.push_str(&format!(
            "    description: \"Staging model for Power BI table '{}'\"\n",
            t.original_name
        ));

        // Columns
        if !t.columns.is_empty() || !t.calc_columns.is_empty() {
            yaml.push_str("    columns:\n");

            for col in &t.columns {
                let col_name = if let Some(ref src) = col.source_column {
                    sanitize_identifier(src)
                } else {
                    sanitize_identifier(&col.name)
                };
                yaml.push_str(&format!("      - name: {col_name}\n"));
                if let Some(ref desc) = col.description {
                    yaml.push_str(&format!("        description: \"{desc}\"\n"));
                }
            }

            for cc in &t.calc_columns {
                yaml.push_str(&format!("      - name: {}\n", cc.name));
                yaml.push_str(&format!(
                    "        description: \"Calculated column (confidence: {:.2})\"\n",
                    cc.confidence
                ));
            }
        }

        // Measures as meta
        if let Some(measures) = dax_translations.measures.get(&t.table_name) {
            if !measures.is_empty() {
                yaml.push_str("    meta:\n");
                yaml.push_str("      measures:\n");
                for m in measures {
                    yaml.push_str(&format!("        - name: {}\n", m.name));
                    yaml.push_str(&format!(
                        "          original_name: \"{}\"\n",
                        m.original_name
                    ));
                    yaml.push_str(&format!(
                        "          confidence: {:.2}\n",
                        m.confidence
                    ));
                    yaml.push_str(&format!(
                        "          sql: |\n            {}\n",
                        m.translated_sql.replace('\n', "\n            ")
                    ));
                    yaml.push_str(&format!(
                        "          original_dax: |\n            {}\n",
                        m.original_dax.trim().replace('\n', "\n            ")
                    ));
                    if m.documentation_only {
                        yaml.push_str("          documentation_only: true\n");
                    }
                }
            }
        }
    }

    // Relationship tests
    if !config.skip_tests && !model.relationships.is_empty() {
        yaml.push('\n');
        // Add tests for relationships
        for t in m_translations {
            let table_rels: Vec<&Relationship> = model
                .relationships
                .iter()
                .filter(|r| sanitize_identifier(&r.from_table) == t.table_name)
                .collect();

            if !table_rels.is_empty() {
                // We need to find this model's section and add tests
                // For simplicity, write a separate test file
            }
        }

        // Write a dbt test schema for relationships
        write_relationship_tests(model, output)?;
    }

    // Write calculated table models schema
    if !dax_translations.calc_tables.is_empty() {
        yaml.push('\n');
        for ct in &dax_translations.calc_tables {
            yaml.push_str(&format!("  - name: int_{}\n", ct.name));
            yaml.push_str(&format!(
                "    description: \"Calculated table from Power BI (confidence: {:.2})\"\n",
                ct.confidence
            ));
        }
    }

    super::write_file(&output.join("models").join("_models.yml"), &yaml)
}

/// Write relationship test definitions.
fn write_relationship_tests(
    model: &SemanticModel,
    output: &Path,
) -> Result<(), PbipError> {
    if model.relationships.is_empty() {
        return Ok(());
    }

    let version = env!("CARGO_PKG_VERSION");
    let mut yaml = String::new();
    yaml.push_str(&format!("# Auto-generated by pbip2dbt v{version}\n"));
    yaml.push_str("# Relationship tests from Power BI model\n");
    yaml.push_str("version: 2\n\n");
    yaml.push_str("models:\n");

    // Group relationships by from_table
    let mut rel_map: std::collections::BTreeMap<String, Vec<&Relationship>> =
        std::collections::BTreeMap::new();
    for rel in &model.relationships {
        rel_map
            .entry(sanitize_identifier(&rel.from_table))
            .or_default()
            .push(rel);
    }

    for (table_name, rels) in &rel_map {
        yaml.push_str(&format!("  - name: stg_{table_name}\n"));
        yaml.push_str("    columns:\n");

        for rel in rels {
            let from_col = sanitize_identifier(&rel.from_column);
            let to_table = sanitize_identifier(&rel.to_table);
            let to_col = sanitize_identifier(&rel.to_column);

            yaml.push_str(&format!("      - name: {from_col}\n"));
            yaml.push_str("        tests:\n");
            yaml.push_str("          - not_null\n");
            yaml.push_str(&format!(
                "          - relationships:\n\
                 \x20             to: ref('stg_{to_table}')\n\
                 \x20             field: {to_col}\n"
            ));
        }

        // Add unique test for to-side columns (primary key side)
        for rel in rels {
            let _to_table = sanitize_identifier(&rel.to_table);
            let _to_col = sanitize_identifier(&rel.to_column);

            // We'll add unique tests for the to-table in a separate entry
        }
    }

    // Add unique tests for referenced tables (to-side)
    let mut to_tables: std::collections::BTreeMap<String, Vec<String>> =
        std::collections::BTreeMap::new();
    for rel in &model.relationships {
        to_tables
            .entry(sanitize_identifier(&rel.to_table))
            .or_default()
            .push(sanitize_identifier(&rel.to_column));
    }

    for (table_name, columns) in &to_tables {
        if !rel_map.contains_key(table_name) {
            yaml.push_str(&format!("  - name: stg_{table_name}\n"));
            yaml.push_str("    columns:\n");
        }
        // Add unique + not_null for PK columns
        let mut seen = std::collections::BTreeSet::new();
        for col in columns {
            if seen.insert(col.clone()) {
                yaml.push_str(&format!("      - name: {col}\n"));
                yaml.push_str("        tests:\n");
                yaml.push_str("          - unique\n");
                yaml.push_str("          - not_null\n");
            }
        }
    }

    super::write_file(
        &output.join("models").join("_relationships_tests.yml"),
        &yaml,
    )
}
