//! Generate dbt `_sources.yml` files.

use crate::config::Config;
use crate::error::PbipError;
use crate::MTranslation;
use std::collections::BTreeMap;
use std::path::Path;

/// Write sources YAML files.
pub fn write_sources(
    config: &Config,
    translations: &[MTranslation],
    source_name: &str,
    output: &Path,
) -> Result<(), PbipError> {
    // Group tables by source
    let mut sources: BTreeMap<String, Vec<SourceTableEntry>> = BTreeMap::new();

    for t in translations {
        let entry = SourceTableEntry {
            name: t.table_name.clone(),
            original_name: t.original_name.clone(),
            description: format!("Auto-imported from Power BI table '{}'", t.original_name),
        };
        sources
            .entry(source_name.to_string())
            .or_default()
            .push(entry);
    }

    for (src_name, tables) in &sources {
        let mut yaml = String::new();
        let version = env!("CARGO_PKG_VERSION");
        yaml.push_str(&format!("# Auto-generated by pbip2dbt v{version}\n"));
        yaml.push_str("version: 2\n\n");
        yaml.push_str("sources:\n");
        yaml.push_str(&format!("  - name: {src_name}\n"));
        yaml.push_str(&format!("    schema: {}\n", config.schema));
        yaml.push_str("    description: >-\n");
        yaml.push_str("      Source tables auto-imported from Power BI semantic model.\n");
        yaml.push_str("    tables:\n");

        for table in tables {
            yaml.push_str(&format!("      - name: {}\n", table.name));
            if table.name != table.original_name {
                yaml.push_str(&format!(
                    "        identifier: '{}'\n",
                    table.original_name
                ));
            }
            yaml.push_str(&format!(
                "        description: \"{}\"\n",
                table.description
            ));
        }

        let filename = format!("_{src_name}__sources.yml");
        super::write_file(&output.join("models").join("staging").join(&filename), &yaml)?;
    }

    Ok(())
}

struct SourceTableEntry {
    name: String,
    original_name: String,
    description: String,
}
